queue_rules:
  - name: default
    queue_conditions:
      - author=scala-steward
      - status-success~=^build \(3
    merge_conditions:
      - check-success~=^build \(3
    merge_method: squash

pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [Billzabob]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions: []
    actions:
      queue:
