addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"            % "1.6.1")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"           % "1.5.7")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                 % "2.2.20")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.5.1")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"          % "0.8.1")
