addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.5")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"            % "1.9.2")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"           % "1.5.10")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                 % "2.2.24")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.7.1")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"          % "1.0.1")
