addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.3.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.5.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"            % "2.0.6")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"           % "1.5.11")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                 % "2.3.6")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.11.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"          % "1.1.1")
