name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 2.12.11
          - 2.13.2
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      if: matrix.scala == '2.13.2'
      run: sbt ++${{ matrix.scala }} scalafmtCheckAll
    - name: Check bincompat
      run: sbt ++${{ matrix.scala }} coreJVM/mimaReportBinaryIssues
    - name: Run tests
      run: sbt ++${{ matrix.scala }} clean test
    - name: Run tests ScalaJS 0.6
      run: sbt ++${{ matrix.scala }} 'project coreJS' clean test
      env:
        SCALAJS_VERSION: 0.6.33
