name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt clean coverage +test coverageReport
    - name: Check formatting
      run: sbt scalafmtCheckAll
    - name: Upload coverage
      uses: codecov/codecov-action@v1
