name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 2.12.13
          - 2.13.4
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      if: matrix.scala == '2.13.4'
      run: sbt ++${{ matrix.scala }} scalafmtCheckAll
    - name: Check bincompat
      run: sbt ++${{ matrix.scala }} coreJVM/mimaReportBinaryIssues
    - name: Run tests
      run: sbt ++${{ matrix.scala }} clean test
