name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 3.0.1
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      if: matrix.scala == '3.0.1'
      run: sbt ++${{ matrix.scala }} scalafmtCheckAll
    # - name: Check bincompat
    #   run: sbt ++${{ matrix.scala }} coreJVM/mimaReportBinaryIssues
    - name: Run tests
      run: sbt ++${{ matrix.scala }} clean test
