name: coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate code coverage
      run: sbt ++3.0.1 'project coreJVM' clean coverage test coverageReport
    - name: Upload coverage
      uses: codecov/codecov-action@v1
